/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_lenovo_myapplication_MainActivity2 */

#ifndef _Included_com_example_lenovo_myapplication_MainActivity2
#define _Included_com_example_lenovo_myapplication_MainActivity2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_lenovo_myapplication_MainActivity2
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_lenovo_myapplication_MainActivity2_getStringFromNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
